name: advanced_weather_app
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    get: ^4.7.2
    geolocator: ^14.0.1
    app_settings: ^6.1.1
    geocoding: ^4.0.0
    http: ^1.4.0
    flutter_typeahead: ^5.2.0
    flutter_dotenv: ^5.2.1
    intl: ^0.20.2
    connectivity_plus: ^6.1.4
    internet_connection_checker: ^3.0.1
    lottie: ^3.3.1
    fl_chart: ^1.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - .env
        - assets/background_weather_app.jpg
        - assets/animations/error/error_animation.json
        - assets/animations/weather/snow.json
        - assets/animations/weather/rain.json
        - assets/animations/weather/cloud.json
        - assets/animations/weather/sunny.json

    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
